### ISSUE TITLE
Setup script with new indices is never called

### ISSUE THREAD

**Issue by phizab** [PAYONE-GmbH/magento-1#412]
I'm wondering why there is a setup script "mysql4-upgrade-4.5.0-4.5.1" while the version in config.xml is still 4.5.0. So the setup script will never be called. Is there a problem with the indices set in this script?

**Comment by phoenix-schwarz** [comment]
related to: https://github.com/PAYONE-GmbH/magento-1/issues/395

and fixed in https://github.com/PAYONE-GmbH/magento-1/pull/400

The version is not released yet AFAIK. See: https://github.com/PAYONE-GmbH/magento-1/releases (4.5.0)

**Comment by phizab** [comment]
But why the script is in master branch, while it will never be executed? In my opinion it is not fixed then. 

Are there any plans for a bugfix release 4.5.1?

**Comment by phoenix-schwarz** [comment]
Have you checked the "released version" - the master branch does not reflect the released version.

**Comment by phizab** [comment]
I know, but I wanted to apply some fixes for issues in 4.5.0 by myself, so I checked the master and was wondering about this script.

OK, I think I have to wait for a new release then. Would be nice to have more small bugfix releases, since 4.5.0 is quite old.
